theme: jekyll-theme-cayman

# Setup
title:            Ilyas Aaqaoui

description:      'A brazen two-column Jekyll theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'

